name: ECZANELERÄ° AL

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir Ã§alÄ±ÅŸtÄ±r

jobs:
  fetch-and-update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
      
    - name: Fetch Data and Update json
      run: |
        node eczane2.js  # Script
        git add Bursa_eczane_data.json
        git add Diyarbakir_eczane_data.json
        git config --global user.email "codermert@bk.ru"
        git config --global user.name "codermert"
        git diff --cached --exit-code --quiet || git commit -m "ðŸ•°  NÃ¶betÃ§i Eczaneler Â» @codermert"
        git push
